baseURL = 'https://studkniit.online'
languageCode = 'ru-ru'
title = 'Курс молодого КНиИТовца'
theme = 'stack'
buildFuture = true

[params]
  description = 'Курс молодого КНиИТовца: материалы, гайды, конспекты, экзамены и полезные ссылки для студентов КНиИТ.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
